(() => {
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const readSessions = () => { try { return JSON.parse(localStorage.getItem('rsm-sessions') || '[]'); } catch { return []; } };
  const toast = message => { const node = document.querySelector('#toast'); node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 3200); };
  const close = () => { document.querySelector('#debriefRoot')?.remove(); };
  function openDebrief() {
    const sessions = readSessions().filter(session => session.status === 'arrived');
    const commitments = sessions.flatMap(session => (session.commitments || []).map(item => ({ ...item, organization: session.organization })));
    const unassigned = commitments.filter(item => !item.owner || !item.dueDate);
    const priorities = sessions.flatMap(session => (session.insights || []).map(item => ({ ...item, organization: session.organization })));
    const rows = commitments.length ? commitments.map(item => `<li><div><strong>${esc(item.organization)}</strong><br>${esc(item.text)}</div><span class="debrief-meta">${esc(item.owner || 'Unassigned')} · ${esc(item.dueDate || 'No date')} · ${esc(item.status || 'Open')}</span></li>`).join('') : '<li class="muted">No commitments captured yet.</li>';
    const insightRows = priorities.length ? priorities.map(item => `<li><strong>${esc(item.organization)}</strong> · ${esc(item.text)}<span class="debrief-meta">${esc(item.status || 'Draft')}</span></li>`).join('') : '<li class="muted">No insights captured yet.</li>';
    document.body.insertAdjacentHTML('beforeend', `<div id="debriefRoot" class="modal-backdrop"><section class="modal modal-wide" role="dialog" aria-modal="true" aria-labelledby="debriefTitle"><div class="modal-header"><div><p class="eyebrow">Daily debrief · Friday, November 13</p><h2 id="debriefTitle">Close the loop</h2><p class="muted">One named owner per client. Resolve gaps before the team leaves the Hub.</p></div><button class="close" aria-label="Close daily debrief">×</button></div><div class="debrief-summary"><div><strong>${sessions.length}</strong><span>sessions completed</span></div><div><strong>${commitments.length}</strong><span>open commitments</span></div><div class="${unassigned.length ? 'attention' : ''}"><strong>${unassigned.length}</strong><span>items needing owner/date</span></div></div><div class="debrief-grid"><section class="dossier-card"><h3>Open commitments</h3><ul class="debrief-list">${rows}</ul></section><section class="dossier-card"><h3>Captured insights</h3><ul class="debrief-list">${insightRows}</ul></section></div><div class="completeness ${unassigned.length ? 'blocked' : 'complete'}"><strong>${unassigned.length ? 'Follow-up needs attention' : 'Debrief completeness check passed'}</strong><span>${unassigned.length ? `${unassigned.length} commitment${unassigned.length === 1 ? '' : 's'} lacks an owner or due date.` : 'Every captured commitment has a named owner and due date.'}</span></div><div class="modal-actions"><button class="button secondary close">Close</button><button class="button" id="exportDebrief">Copy debrief summary</button></div></section></div>`);
    document.querySelectorAll('#debriefRoot .close').forEach(button => button.addEventListener('click', close));
    document.querySelector('#exportDebrief').addEventListener('click', async () => { const text = `RSM Classic Daily Debrief\nSessions: ${sessions.length}\nOpen commitments: ${commitments.length}\nNeeds attention: ${unassigned.length}\n\n${commitments.map(item => `- ${item.organization}: ${item.text} | ${item.owner || 'Unassigned'} | ${item.dueDate || 'No date'}`).join('\n')}`; try { await navigator.clipboard.writeText(text); toast('Debrief summary copied'); } catch { toast('Copy unavailable on this device'); } });
  }
  document.addEventListener('DOMContentLoaded', () => document.querySelector('#debriefButton')?.addEventListener('click', openDebrief));
})();
